import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider, RedirectToSignIn, SignedOut } from "@clerk/nextjs";
import Head from "next/head";
import { ChartColumn, Plus, Table } from "lucide-react";
import { FloatingDock } from "@/components/ui/dock";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const dockItems = [
        {
            title: "Overview",
            icon: <ChartColumn className="h-full w-full" />,
            href: "/expenses",
        },
        {
            title: "List",
            icon: <Table className="h-full w-full" />,
            href: "/expenses/all",
        },
        {
            title: "Add Expense",
            icon: <Plus className="h-full w-full" />,
            href: "#",
        },
    ];

    return (
        <ClerkProvider>
            <html lang="en">
                <Head>
                    <meta name="viewport" content="user-scalable=no" />
                    <link rel="manifest" href="/site.webmanifest" />
                </Head>
                <body
                    className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                    <SignedOut>
                        <RedirectToSignIn />
                    </SignedOut>
                    <div className="flex flex-1 flex-col gap-4 p-4 lg:px-6">
                        {children}
                        <div className="fixed bottom-4 right-4">
                            <FloatingDock items={dockItems} />
                        </div>
                    </div>
                </body>
            </html>
        </ClerkProvider>
    );
}
